docs/supported_inventory_types.md, extractor/filesystem/language/cpp/conanlock/extractor-v1-revisions_test.go, extractor/filesystem/language/cpp/conanlock/extractor-v1_test.go, extractor/filesystem/language/cpp/conanlock/extractor-v2_test.go, extractor/filesystem/language/cpp/conanlock/extractor.go, extractor/filesystem/language/cpp/conanlock/extractor_test.go, extractor/filesystem/language/cpp/conanlock/testdata/empty.v1.json, extractor/filesystem/language/cpp/conanlock/testdata/empty.v1.revisions.json, extractor/filesystem/language/cpp/conanlock/testdata/empty.v2.json, extractor/filesystem/language/cpp/conanlock/testdata/nested-dependencies.v1.json, extractor/filesystem/language/cpp/conanlock/testdata/nested-dependencies.v1.revisions.json, extractor/filesystem/language/cpp/conanlock/testdata/nested-dependencies.v2.json, extractor/filesystem/language/cpp/conanlock/testdata/no-name.v1.json, extractor/filesystem/language/cpp/conanlock/testdata/no-name.v1.revisions.json, extractor/filesystem/language/cpp/conanlock/testdata/no-name.v2.json, extractor/filesystem/language/cpp/conanlock/testdata/not-json.txt, extractor/filesystem/language/cpp/conanlock/testdata/old-format-0.0.json, extractor/filesystem/language/cpp/conanlock/testdata/old-format-0.1.json, extractor/filesystem/language/cpp/conanlock/testdata/old-format-0.2.json, extractor/filesystem/language/cpp/conanlock/testdata/old-format-0.3.json, extractor/filesystem/language/cpp/conanlock/testdata/one-package-dev.v1.json, extractor/filesystem/language/cpp/conanlock/testdata/one-package-dev.v1.revisions.json, extractor/filesystem/language/cpp/conanlock/testdata/one-package-dev.v2.json, extractor/filesystem/language/cpp/conanlock/testdata/one-package.v1.json, extractor/filesystem/language/cpp/conanlock/testdata/one-package.v1.revisions.json, extractor/filesystem/language/cpp/conanlock/testdata/one-package.v2.json, extractor/filesystem/language/cpp/conanlock/testdata/two-packages.v1.json, extractor/filesystem/language/cpp/conanlock/testdata/two-packages.v1.revisions.json, extractor/filesystem/language/cpp/conanlock/testdata/two-packages.v2.json, extractor/filesystem/list/list.go
Migrate CPP Conan lockfile extractor.
=> feat: Conan lock migration

.github/codeql-analysis.yml
=> ci: setup codeql

extractor/filesystem/language/golang/gobinary/gobinary.go
Checks if there is a readerAt, if not, copy everything into a buffer which does implement readerAt.
=> Gobinary extractor should not expect to get a ReaderAt

artifact/image/layerscanning/image/image.go
Ideally we will have more coverage extracting actual images in tests to catch these cases.
=> fix: Fixes to filepaths for container extraction on windows

semantic/compare_test.go, semantic/version-cran.go, semantic/version-pypi.go, semantic/version-semver-like.go
=> refactor(semantic): avoid shadowing variables and types

extractor/filesystem/internal/walkdir_iterate.go
Addresses [this comment](https://github.com/google/osv-scalibr/pull/467#discussion_r1961698476)
=> fix: surface possible error when closing file during directory walking

extractor/filesystem/filesystem.go
Addresses [this comment](https://github.com/google/osv-scalibr/pull/467#discussion_r1961696809)
=> fix: surface possible error when attempting to copy file on filesystem as part of getting real path

go.mod, go.sum, internal/guidedremediation/remediation/remediation.go, internal/guidedremediation/remediation/remediation_test.go, internal/guidedremediation/severity/severity.go, internal/guidedremediation/severity/severity_test.go
Adds back in the logic for filtering vulnerabilities based on severity.
=> feat(guided remediation): Add vuln severity matching

.golangci.yaml, detector/cve/cve202011978/cve202011978.go, detector/cve/cve202016846/cve202016846.go, detector/cve/cve202233891/cve202233891.go, detector/cve/cve20236019/cve20236019.go, detector/cve/cve20242912/cve20242912.go, detector/weakcredentials/filebrowser/filebrowser.go
=> refactor: use stdlib variables for http constants

.golangci.yaml
=> chore: enable `dupl` linter

go.mod
`go mod tidy` wants these flipped
=> chore: tidy `go.mod`

binary/cli/cli.go, detector/cve/cve202016846/cve202016846.go, extractor/filesystem/containers/containerd/containerd_dummy.go, extractor/filesystem/os/rpm/rpm_dummy.go, extractor/standalone/containers/containerd/containerd_dummy.go, extractor/standalone/os/netports/netports_dummy.go
This slipped through due to the merge order and age of #527 - no biggie though, it was bound to happen at least once 😅
=> perf: use `errors.New` and simple string concatenation

extractor/filesystem/misc/vscodeextensions/vscodeextensions_test.go
This fixes a linting violation introduced in #533
=> refactor: remove leading newline

artifact/image/layerscanning/image/image.go
=> refactor: explicitly mark error as ignored

common/linux/proc/proc_dummy.go, extractor/filesystem/containers/containerd/containerd_dummy.go, extractor/filesystem/os/rpm/rpm_dummy.go, extractor/standalone/containers/containerd/containerd_dummy.go, extractor/standalone/containers/containerd/fakeclient/fake_containerd_client_dummy.go, extractor/standalone/os/netports/netports_dummy.go
=> chore: add package comments to OS-specific files

.golangci.yaml, artifact/image/tar/tar_test.go, artifact/image/whiteout/whiteout.go, extractor/filesystem/language/java/pomxmlnet/pomxmlnet.go, extractor/filesystem/language/javascript/bunlock/bunlock.go, extractor/filesystem/language/javascript/pnpmlock/pnpmlock.go, extractor/filesystem/language/javascript/yarnlock/yarnlock.go, scalibr.go, testing/fakefs/fake_fileinfo_test.go
=> refactor: simplify code where possible

.golangci.yaml, extractor/filesystem/filesystem_test.go
=> refactor: enable `govet` and add field names to struct

binary/proto/proto_test.go, extractor/standalone/containers/docker/docker_test.go, go.mod, go.sum
Update github.com/docker/docker to the latest version, which should fix build issue not finding the correct types.
=> fix: Update docker dependency version (also resolves some vulns)

binary/spdx/spdx_test.go, binary/spdx/testdata/json-format.spdx.json, binary/spdx/testdata/tag-value-format.spdx, binary/spdx/testdata/yaml-format, converter/converter.go, converter/converter_test.go
=> Use SPDXRef-DOCUMENT to describe root node in SPDX

guidedremediation/internal/manifest/maven/pomxml.go
https://github.com/google/osv-scanner/pull/1856
=> feat: guess the indentation for <dependency> element when writing XML

extractor/filesystem/language/ruby/gemfilelock/gemfilelock.go, extractor/filesystem/language/ruby/gemfilelock/gemfilelock_test.go
This PR adds support for `gems.locked`.
=> feat: Add support for 'gems.locked'

.golangci.yaml, detector/list/list.go, enricher/enricherlist/list.go, extractor/filesystem/language/golang/gomod/gomod.go, extractor/filesystem/language/golang/gomod/gomod_test.go, extractor/filesystem/language/java/pomxml/pomxml.go, extractor/filesystem/language/java/pomxml/pomxml_test.go, extractor/filesystem/language/java/pomxmlnet/pomxmlnet.go, extractor/filesystem/language/java/pomxmlnet/pomxmlnet_test.go, extractor/filesystem/language/javascript/packagelockjson/packagelockjson.go, extractor/filesystem/language/python/pipfilelock/pipfilelock.go, extractor/filesystem/language/python/pipfilelock/pipfilelock_test.go, extractor/filesystem/list/list.go, extractor/standalone/list/list.go, go.mod, go.sum
=> refactor: use stable versions of standard libraries

guidedremediation/internal/strategy/relax/relaxer/npm.go
There are multiple places that we parse a version string to `semver.Version`, and parsing can be expensive sometimes.
This PR minimizes the number of parsing by only parses the versions once and store in slice, however, there is no noticeable performance improvements.
=> refactor: only parse versions once in npm relaxer

.golangci.yaml, testing/fakefs/symlink_fs.go
=> chore: enable `gocritic` linter

.golangci.yaml, artifact/image/layerscanning/image/image.go, semantic/version-debian.go
=> refactor: lift early breaks into loop condition

.golangci.yaml, extractor/filesystem/os/nix/nix_test.go, guidedremediation/guidedremediation.go
=> refactor: omit types that can be inferred

.golangci.yaml, extractor/filesystem/internal/walkdir_iterate_test.go
=> test: use `t.Chdir`

semantic/utilities.go, semantic/version-pypi.go, semantic/version-redhat.go, semantic/version-rubygems.go, semantic/version-semver-like.go
I noticed this while working on other stuff
=> refactor(semantic): reuse existing function rather than regex for checking digits
