google/osv-scalibr

README.md

Update installation instructions to install protoc precompiled binaries instead of the outdated Apt package (see [this issue](https://github.com/google/osv-scalibr/issues/32) for context).

Update README.md for Ubuntu 18.04 installation

---

README.md

It seems fs.FS interface is not used anymore, just the string path of the root directory.

Update documentation related to specifying the filesystem and directory.

---

detector/govulncheck/binary/detector.go
detector/govulncheck/binary/detector_test.go
detector/govulncheck/binary/message.go
detector/govulncheck/binary/testdata/vulndb/ID/GO-2024-2887.json
detector/govulncheck/binary/testdata/vulndb/index/modules.json
detector/govulncheck/binary/testdata/vulndb/index/vulns.json

Currently, every single OSV reported by govulncheck JSON is converted to a scalibr finding. This seems incorrect. govulncheck JSON will emit all OSVs that apply to module dependencies, regardless of the version at which the binary is using them. The results of version checking manifest as govulncheck findings at the scan module level. Further, we are interested in govulncheck findings at the scan symbol level. This CL takes govulncheck findings at the symbol level (i.e., detected symbols in the binary) and converts those to scalibr findings.
We also add tests that fail for the code before this change, but succeed with this change.

detector/binary/govulncheck: report only symbol level vulns

---

binary/cdx/cdx.go
binary/cdx/cdx_test.go
binary/cdx/testdata/doc.cyclonedx.json
binary/cdx/testdata/doc.cyclonedx.xml
binary/cli/cli.go
binary/cli/cli_test.go
binary/scalibr.go
converter/converter.go
converter/converter_test.go
go.mod
go.sum

SPDX format is already supported, but not CycloneDX: https://cyclonedx.org/ This patch adds the ability to export a JSON or XML cycloneDX BOM.
The SBOM is pretty basic for now (ex.: just the components, not the deps), but enough for doing VM.
Test plan: added unit tests
Manual testing:
```
$ ./scalibr -o cdx-json=/tmp/result.cyclonedx.json --root ~/test
2024/07/09 17:43:27 Scan status: SUCCEEDED
2024/07/09 17:43:27 Found 7513 software inventories, 0 security findings
2024/07/09 17:43:27 Writing scan results to /tmp/result.cyclonedx.json
$ jq -e < /tmp/result.cyclonedx.json >/dev/null
$ echo $?
0
```

Add CycloneDX export option

---

.editorconfig
.gitignore

Add .gitignore and .editorconfig (mostly copied from osv-scanner) to make it easier to develop with common IDEs.
This also tests the copybara integration from github's side.

chore: Add a gitignore and .editorconfig file

---

README.md

Generated via https://pkg.go.dev/badge/?path=https%3A%2F%2Fpkg.go.dev%2Fgithub.com%2Fgoogle%2Fosv-scalibr
It makes it easier to find the nicely-formatted documentation.  :grin:

Add GoDoc link

---

docs/supported_inventory_types.md
extractor/filesystem/language/python/pipfilelock/extractor.go
extractor/filesystem/list/list.go
extractor/filesystem/list/list_test.go

Add the newly added python extractors to list.go, and update the documentation accordingly.
This does change the name of python/Pipfile extractor to python/Pipfilelock. This is required as in the future we likely would want to add an actual python/Pipfile extractor.

feat: Add python extractors to list and documentation

---

extractor/filesystem/language/golang/gomod/extractor.go
extractor/filesystem/language/java/gradlelockfile/extractor.go
extractor/filesystem/language/java/gradleverificationmetadataxml/extractor.go
extractor/filesystem/language/java/pomxml/extractor.go
extractor/filesystem/language/javascript/pnpmlock/extractor.go
extractor/filesystem/language/php/composerlock/extractor.go
extractor/filesystem/language/python/pdmlock/extractor.go
extractor/filesystem/language/python/pipfilelock/extractor.go
extractor/filesystem/language/python/poetrylock/extractor.go
extractor/filesystem/language/r/renvlock/extractor.go
extractor/filesystem/language/rust/cargolock/extractor.go

Inline all the ecosystem strings in the extractors migrated from osv-scanner.

refactor: Inline the ecosystem consts

---

binary/spdx/spdx.go
binary/spdx/testdata/json-format.spdx.json

Indent the spdx-json format to improve readability
See the changes in `binary/spdx/testdata/json-format.spdx.json` for a preview

feat: Indent spdx23-json output

---

artifact/image/image.go
binary/cli/cli.go
binary/cli/cli_test.go
binary/scalibr/scalibr.go

When using `--remote-image`, `--image-platform` flag allows SCALIBR to pull images from platforms other than the host's
Currently on a Linux machine:
```
> scalibr -o spdx23-json=result.spdx.json --remote-image  mcr.microsoft.com/windows/nanoserver:ltsc2022 --image-platform windows/amd64
2024/10/31 14:51:24 &{  [spdx23-json=result.spdx.json] default default []   mcr.microsoft.com/windows:ltsc2019        false false true false false}.GetScanConfig(): couldn’t pull remote image mcr.microsoft.com/windows:ltsc2019: no child with platform linux/amd64 in index mcr.microsoft.com/windows:ltsc2019
```
Using `--image-platform`
```
> scalibr -o spdx23-json=result.spdx.json --remote-image  mcr.microsoft.com/windows/nanoserver:ltsc2022 --image-platform windows/amd64
...
(generates a SBOM)
```

feat: Add --image-platform flag

---

.github/workflows/go.yml

ci: upgrade `actions/checkout` to v4

---

.github/workflows/go.yml

Using a matrix for this makes it easier to maintain, especially when we're wanting to add macOS to the list (which I'll do as a follow-up)
Relates to #152

ci: use a matrix for running tests across different operating systems

---

.golangci.yaml
README.md
binary/cdx/cdx.go
binary/cli/cli.go
detector/cve/cve202011978/detector.go
detector/weakcredentials/etcshadow/cracker_test.go
detector/weakcredentials/winlocal/systemreg/systemreg.go
extractor/filesystem/language/dart/pubspec/extractor.go
extractor/filesystem/language/java/archive/manifest.go
extractor/filesystem/language/javascript/pnpmlock/extractor.go

Enabling this linter actually only caught "choosen" but I also ran my IDEs spell/grammer checker which found a few more things
Relates to #152

refactor: enable `misspell` linter

---

.github/workflows/go.yml

Due to the size of this codebase, `golangci-lint` requires more time to compile everything and run the linters - hopefully 5 minutes will be enough

ci: increase timeout for golangci-lint

---

.golangci.yaml
detector/detector_test.go
scalibr_test.go
testing/fakedetector/fake_detector.go

This enables the `predeclared` linter which catches variables whose names clash with predeclared identifiers, as that can be confusing.
Currently the only violation was a few variables being named `copy` which I've renamed to `c` since they have a very short local lifespan
Relates to #152

refactor: enable `predeclared` linter

---

.golangci.yaml
artifact/image/layerscanning/image_test.go
artifact/image/layerscanning/layer_test.go
artifact/image/symlink/symlink.go
artifact/image/symlink/symlink_test.go
artifact/image/tar/tar.go
artifact/image/tar/tar_test.go
artifact/image/unpack/unpack.go
artifact/image/unpack/unpack_test.go
detector/weakcredentials/filebrowser/filebrowser.go
extractor/filesystem/language/java/groupid/groupid_test.go
extractor/filesystem/language/javascript/packagejson/packagejson_test.go
extractor/filesystem/os/macapps/macapps_test.go
extractor/standalone/containers/containerd/containerd_linux.go
extractor/standalone/containers/containerd/fakeclient/fake_containerd_client.go
testing/fakeextractor/fake_extractor.go

This enables the `whitespace` linter, which helps to keep code consistent by reporting unnecessary newlines at the start and end of bodies for functions, ifs, fors, etc

refactor: enable `whitespace` linter

---

.golangci.yaml
binary/cdx/cdx_test.go
detector/list/list.go
extractor/filesystem/list/list.go
extractor/standalone/list/list.go

This enables the `gochecknoinits` linter to strong discourage the usage of `init` functions as while they do sometimes have their usages (and are even necessary), overuse tends to lead to very brittle code.

chore: enable `gochecknoinits` linter

---

.golangci.yaml

This enables the `dupword` linter which catches duplicate word usage like "the the" - we actually don't have any violations as I took care of them in #263

chore: enable `dupword` linter

---

.golangci.yaml
extractor/filesystem/language/cpp/conanlock/conanlock-v1-revisions_test.go
extractor/filesystem/language/cpp/conanlock/conanlock-v1_test.go
extractor/filesystem/language/cpp/conanlock/conanlock-v2_test.go
extractor/filesystem/language/cpp/conanlock/conanlock_test.go
extractor/filesystem/language/erlang/mixlock/mixlock_test.go
extractor/filesystem/language/java/gradlelockfile/gradlelockfile_test.go
extractor/filesystem/language/java/gradleverificationmetadataxml/gradleverificationmetadataxml_test.go
extractor/filesystem/language/java/pomxml/pomxml_test.go
extractor/filesystem/language/javascript/pnpmlock/pnpmlock-v9_test.go
extractor/filesystem/language/javascript/pnpmlock/pnpmlock_test.go
extractor/filesystem/language/php/composerlock/composerlock_test.go
extractor/filesystem/language/python/pdmlock/pdmlock_test.go
extractor/filesystem/language/python/pipfilelock/pipfilelock_test.go
extractor/filesystem/language/python/poetrylock/poetrylock_test.go
extractor/filesystem/language/r/renvlock/renvlock_test.go

This enables the `copyloopvar` to ensure that variables are not needless copied in relation to loops which was a common practice before Go 1.22 as variables prior to that version were created once and updated by each iteration, whereas now they're (re)created on each iteration.
This most commonly presented in testing tables so unsurprisingly that's where all of our violations are

refactor: enable `copyloopvar` linter

---

extractor/filesystem/language/python/poetrylock/poetrylock.go
extractor/filesystem/language/python/poetrylock/poetrylock_test.go

Per [this comment](https://github.com/google/osv-scalibr/pull/314#discussion_r1869927155), we only want to be setting this if we actually know what the commit is

fix(poetrylock): don't set `SourceCode` field unless commit is actually present

---

.golangci.yaml
artifact/image/layerscanning/file_node_test.go
artifact/image/layerscanning/layer_test.go
artifact/image/unpack/unpack.go
detector/cve/cve202338408/semantic/version-packagist.go
detector/cve/cve20236019/cve20236019.go
detector/weakcredentials/winlocal/samreg/crypto.go
detector/weakcredentials/winlocal/systemreg/systemreg.go

This enables the `intrange` linter which enforces the use of integer-based `range`s where possible, as they're generally cleaner

refactor: use integer-based `range`s where possible

---

.golangci.yaml
extractor/filesystem/containers/containerd/containerd_linux.go
extractor/filesystem/containers/containerd/containerd_test.go
extractor/standalone/windows/dismpatch/dismpatch.go

This enables the `unconvert` linter which ensures conversions are actually necessary, which helps to keep things readable by reducing the amount of code and potentially even being slightly more performant

refactor: remove unnecessary type conversions

---

.golangci.yaml
artifact/image/tar/tar_test.go
artifact/image/unpack/unpack_test.go
extractor/filesystem/containers/containerd/containerd_test.go
extractor/filesystem/os/rpm/rpm_test.go
extractor/filesystem/sbom/cdx/cdx_test.go

This enables the `thelper` linter which ensures helper functions actually call `t.Helper` so that test failures report the test itself as the failure rather than the helper, making it easier to track down what actually failed.

test: ensure that `t.Helper` is used

---

.golangci.yaml
artifact/image/image.go
artifact/image/layerscanning/image.go
artifact/image/tar/tar.go
artifact/image/tar/tar_test.go
artifact/image/unpack/unpack.go
artifact/image/unpack/unpack_test.go
detector/weakcredentials/winlocal/samreg/samreg.go

This enables the `goimports` linter to ensure our imports are consistently and well formatted, which most already are

refactor: apply `goimports` linter

---

.golangci.yaml
detector/weakcredentials/etcshadow/cracker.go

This enables the `inamedparam` linter which ensures all interface methods name their parameters, to help make it clear what they're intended for

refactor: name parameters in `Cracker` interface

---

.golangci.yaml
extractor/filesystem/language/cpp/conanlock/conanlock-v1-revisions_test.go
extractor/filesystem/language/cpp/conanlock/conanlock-v1_test.go
extractor/filesystem/language/cpp/conanlock/conanlock-v2_test.go
extractor/filesystem/language/cpp/conanlock/conanlock_test.go
extractor/filesystem/language/golang/gomod/gomod_test.go
extractor/filesystem/language/java/gradlelockfile/gradlelockfile_test.go
extractor/filesystem/language/java/gradleverificationmetadataxml/gradleverificationmetadataxml_test.go
extractor/filesystem/language/java/pomxml/pomxml_test.go
extractor/filesystem/language/javascript/packagelockjson/packagelockjson-v1_test.go
extractor/filesystem/language/javascript/packagelockjson/packagelockjson-v2_test.go
extractor/filesystem/language/javascript/packagelockjson/packagelockjson_test.go
extractor/filesystem/language/javascript/pnpmlock/pnpmlock-v9_test.go
extractor/filesystem/language/javascript/pnpmlock/pnpmlock_test.go
extractor/filesystem/language/javascript/yarnlock/yarnlock-v2_test.go
extractor/filesystem/language/php/composerlock/composerlock_test.go
extractor/filesystem/language/python/pdmlock/pdmlock_test.go
extractor/filesystem/language/python/pipfilelock/pipfilelock_test.go
extractor/filesystem/language/python/poetrylock/poetrylock_test.go
extractor/filesystem/language/r/renvlock/renvlock_test.go
extractor/filesystem/language/ruby/gemfilelock/gemfilelock_test.go
extractor/filesystem/language/rust/cargolock/cargolock_test.go
scalibr_test.go
testing/extracttest/compare_test.go

The internal test runner used by Google gets confused by testing using `t.Parallel` due to the log lines getting mixed, so this removes all usage of it and configures the `forbidigo` linter to enforce it's not-use.
Since this by extension means we never want the `tparallel` linter enabled, I've updated the linting config to remove it from the `enable` list and added it to the commented out `disable` list in preparation for when we're able to switch to having all linters enabled by default (as you're not allowed to use both `disable-all` and `disable` at the same time)

test: forbid using `t.Parallel`

---

.github/workflows/go.yml

This adds a new temporary job that runs `golangci-lint` with `only-new-issues` enabled in the hopes that it'll reduce friction for contributions being made via GitHub by avoiding failing CI due to linting violations introduced through internal patches.
As I've not had a lot of experience with this option and an incorrect setup with linters can often look the same as linting being happy unless someone actually takes the time to review the logs of every run, I've opted to start by introducing this as a second job with the idea being we'll get the see what the linter would give us with and without that option.
I expect after a bunch of pull requests, we'll have seen enough to decide if this option would actually be helpful, and either way remove one of the two jobs
Relates to #346

ci: explore running linting on just new changes

---

.golangci.yaml
Makefile

By default `golangci-lint` only reports the first 50 issues per linter and the first 3 issues that have the same text which is noble but in my experience tends to make it more tedious to deal with long-term as you'll think you've addressed all the linting errors only to find new ones being reported that weren't previously and it also can result in easy-to-address errors being hidden if they come after more complicated ones.

ci: report all linting errors at once

---

artifact/image/layerscanning/image/file_node.go
artifact/image/layerscanning/image/file_node_test.go

The gobinary extractor expects a ReaderAt, but fileNode does not implement it. The underlying file does though, so this just exposes it.

feat: Add ReadAt function for fileNode to allow gobinary extractor to successfully extract.

---

.github/workflows/go.yml

In my experience this tends to be a better experience as cancelling the other jobs means you can't easily confirm if the failure is OS-specific

ci: don't cancel other test jobs if one fails

---

.golangci.yaml
artifact/image/whiteout/whiteout.go

This linter aims to catch mix ups in returns for errors on branches that have asserted an error wasn't `nil`, as usually you want to be returning an error even if it's not the original one or otherwise you'd not have the function return an error in the first place.
Of course, our one violation of this linter happens to be an exception to the rule: `fs.WalkDir` takes `nil` to mean "thanks for letting us know, now continue with the rest of the walk" for cases where it can't walk a particular path.

chore: enable `nilerr` linter

---

artifact/image/layerscanning/image/layer.go
artifact/image/layerscanning/image/layer_test.go

FromString actually hashes the string, Digest itself is already a wrapper around a string, so to turn a string directly into a digest just cast it.
We need some snapshot-like tests for container scanning to catch these behavioural changes before they get merged.
Oh wait, we had the tests, just missed it in the review.

fix: Fix diffids being wrongly generated

---

extractor/filesystem/language/cpp/conanlock/conanlock-v1_test.go
extractor/filesystem/language/cpp/conanlock/conanlock.go
extractor/filesystem/language/golang/gobinary/gobinary.go
extractor/filesystem/language/java/gradlelockfile/gradlelockfile.go
extractor/filesystem/language/java/gradleverificationmetadataxml/gradleverificationmetadataxml.go
extractor/filesystem/language/java/gradleverificationmetadataxml/gradleverificationmetadataxml_test.go
extractor/filesystem/language/java/pomxml/pomxml.go
extractor/filesystem/language/java/pomxml/pomxml_test.go
extractor/filesystem/language/javascript/pnpmlock/pnpmlock.go
extractor/filesystem/language/javascript/pnpmlock/pnpmlock_test.go
extractor/filesystem/language/php/composerlock/composerlock.go
extractor/filesystem/language/php/composerlock/composerlock_test.go
extractor/filesystem/language/python/pdmlock/pdmlock.go
extractor/filesystem/language/python/pdmlock/pdmlock_test.go
extractor/filesystem/language/python/pipfilelock/pipfilelock.go
extractor/filesystem/language/python/pipfilelock/pipfilelock_test.go
extractor/filesystem/language/python/poetrylock/poetrylock.go
extractor/filesystem/language/python/poetrylock/poetrylock_test.go
extractor/filesystem/language/r/renvlock/renvlock.go
extractor/filesystem/language/r/renvlock/renvlock_test.go
extractor/filesystem/language/rust/cargolock/cargolock.go
extractor/filesystem/language/rust/cargolock/cargolock_test.go

This ensures we're more consistent, and is the result of discussions on [#379](https://github.com/google/osv-scalibr/pull/379#discussion_r1916805117)

fix: ensure extractors return a `nil` slice when erroring

---

.golangci.yaml
detector/govulncheck/binary/message.go

While tags are technically not required, it's recommended to always include them so that changes to the structure of the struct on the Go side do not immediately change the field being used when (un)marshalling from an external data source.

refactor: ensure that all fields in (un)marshaled structs have tags

---

extractor/filesystem/language/javascript/pnpmlock/pnpmlock_test.go
extractor/filesystem/language/javascript/pnpmlock/testdata/invalid-paths.yaml

This ensures that the extractor will return everything it's managed to extract successfully in the event of a recoverable error extracting a specific package, and that it also includes all the errors in its output

test(pnpmlock): cover partial extraction and multiple error cases

---

.golangci.yaml
extractor/filesystem/os/rpm/rpm_linux.go
extractor/standalone/containers/containerd/containerd_linux.go

This enables the `contextcheck` linter which ensures we're properly inheriting our contexts when appropriate - for the existing violations, I've refactored the code to reuse contexts that are nearby which feels like the right thing to do, but I'm not super experienced with managing contexts so maybe it's the wrong thing to do 😅

refactor: reuse existing context where possible

---

.golangci.yaml
extractor/filesystem/filesystem.go
testing/fakeextractor/fake_extractor_test.go

This linter discourages the usage of `context.Context` fields on structs which is generally considered [bad practice](https://go.dev/blog/context-and-structs).

chore: enable `containedctx` linter

---

extractor/filesystem/language/python/uvlock/testdata/empty.lock
extractor/filesystem/language/python/uvlock/testdata/grouped-packages.lock
extractor/filesystem/language/python/uvlock/testdata/no-dependencies.lock
extractor/filesystem/language/python/uvlock/testdata/no-packages.lock
extractor/filesystem/language/python/uvlock/testdata/not-toml.txt
extractor/filesystem/language/python/uvlock/testdata/one-package.lock
extractor/filesystem/language/python/uvlock/testdata/source-git.lock
extractor/filesystem/language/python/uvlock/testdata/two-packages.lock
extractor/filesystem/language/python/uvlock/uvlock.go
extractor/filesystem/language/python/uvlock/uvlock_test.go
extractor/filesystem/list/list.go
extractor/filesystem/list/list_test.go

This adds support for parsing [`uv.lock` files](https://docs.astral.sh/uv/concepts/projects/layout/#the-lockfile) which are TOML based and overall seem pretty straightforward - the main gotcha I came across was that they nest their "groups" table (called `optional-dependencies`) in the `package` array of tables (I think those are the right TOML terms), meaning it actually ends up getting stuck on the _last_ "package" entry even though it is not package specific.
Beyond that, I think the main two areas that could do with expanding are:
* support for more exoitc dependencies ~such as `git`~ (I [figured this out](https://docs.astral.sh/uv/concepts/projects/dependencies/#git))
* support groups - it looks like `uv` only tracks the direct dependency that has been grouped, but does not mark …

feat: support extracting from `uv.lock`

---

artifact/image/layerscanning/image/file_node.go
artifact/image/layerscanning/image/file_node_test.go

Similar to #371, instead this time is to support the Archive extractor. I think this is the last main io interface we need to implement.

feat: Add seek function to fileNode

---

artifact/image/layerscanning/trace/trace.go

@mleyvajr100 FYI this will change the log output quite a bit.
I also updated slightly how traceback works with inventories that contain multiple locations. From what I understand for filesystem extraction only the first Location is the location that the initial walk extracts, and the following locations are just additional information that is obtained from that initial first file. 
Therefore we should only extract the first file during traceback.

fix: Stop error logging during traceback.

---

extractor/filesystem/language/java/archive/archive.go
extractor/filesystem/language/java/archive/archive_test.go

Currently archive extractor saves the path within the jar file (appended to the jar file path) as the Location of the inventory, which is a path that does not exist on disk. 
This moves it to a secondary location, so the first location is a real path.

fix: Archive extraction path correctly points to the jar file that's being extracted

---

extractor/filesystem/language/javascript/yarnlock/yarnlock.go
extractor/filesystem/language/javascript/yarnlock/yarnlock_test.go

This mirrors the behaviour of `packagelockjson`, so I think it should be applied here too as I don't know of any tool which respects lockfiles in `node_modules`.
This _might_ fix https://github.com/google/osv-scalibr/issues/400

fix(yarnlock): ignore `yarn.lock` files in `node_modules`

---

extractor/filesystem/language/javascript/bunlock/bunlock.go
extractor/filesystem/language/javascript/bunlock/bunlock_test.go

This mirrors the behaviour of `packagelockjson`, so I think it should be applied here too as I don't know of any tool which respects lockfiles in `node_modules`.

fix(bunlock): ignore `bun.lock` files in `node_modules`

---

extractor/filesystem/language/javascript/pnpmlock/pnpmlock.go
extractor/filesystem/language/javascript/pnpmlock/pnpmlock_test.go

This mirrors the behaviour of `packagelockjson`, so I think it should be applied here too as I don't know of any tool which respects lockfiles in `node_modules`.

fix(pnpmlock): ignore `pnpm-lock.yaml` files in `node_modules`

---

extractor/filesystem/language/java/javalockfile/metadata.go
extractor/filesystem/language/java/pomxml/pomxml.go
extractor/filesystem/language/java/pomxml/pomxml_test.go
extractor/filesystem/language/java/pomxml/testdata/with-type-classifier.xml
purl/purl.go

https://github.com/google/osv-scalibr/issues/426
This PR adds Maven `type` and `classifier` to PURL qualifiers in the basic `pomxml` extractor.

feat: add Maven type and classifier to PURL qualifiers

---

.github/workflows/go.yml

#399 moved us to Go v1.23 but did not update CI to use that version, so that's what this does

ci: use Go v1.23

---

go.mod

This dependency is actually being used directly

refactor: run `go mod tidy`

---

extractor/filesystem/sbom/cdx/cdx.go
extractor/filesystem/sbom/cdx/cdx_test.go
extractor/filesystem/sbom/spdx/spdx.go
extractor/filesystem/sbom/spdx/spdx_test.go

This fixes the current implementation to correctly identify SBOM files that fit the spec, and discard non spec filenames.
Removes support for:
```
*.bom.json
*.bom.spdx
```
Adds support for:
```
bom.json
bom.spdx
spdx.rdf.xml (Official example is a file with .xml extension)
```
https://cyclonedx.org/specification/overview/#recognized-file-patterns
https://spdx.dev/learn/overview/#documents
Related: https://github.com/google/osv-scanner/discussions/1529#discussioncomment-12017733

fix: FileRequired for SBOM extractors to correctly identify names based on spec

---

.golangci.yaml
artifact/image/whiteout/whiteout.go

Tweak the comments a bit to make it pass both the public and internal linters.

chore: make `nolint` in its own line

---

clients/datasource/maven_registry.go
extractor/filesystem/language/java/pomxmlnet/pomxmlnet.go
extractor/filesystem/list/list.go

Maven Central has quite strict rate limit, we probably want switch to [Maven Central mirror](https://storage-download.googleapis.com/maven-central/index.html) considering the internal use case.

feat: use Maven Central mirror as the registry for pomxmlnet extractor

---

internal/guidedremediation/manifest/manifest.go
internal/guidedremediation/manifest/maven/pomxml.go
internal/guidedremediation/manifest/maven/pomxml_test.go
internal/guidedremediation/manifest/maven/testdata/my-app/pom.xml
internal/guidedremediation/manifest/maven/testdata/parent/grandparent/mismatch.xml
internal/guidedremediation/manifest/maven/testdata/parent/grandparent/pom.xml
internal/guidedremediation/manifest/maven/testdata/parent/pom.xml
internal/guidedremediation/manifest/npm/packagejson.go
internal/guidedremediation/manifest/npm/packagejson_test.go
internal/guidedremediation/manifest/npm/testdata/package.json
internal/guidedremediation/manifest/npm/testdata/workspaces/package.json
internal/guidedremediation/manifest/npm/testdata/workspaces/ws/jquery/package.json
internal/guidedremediation/manifest/npm/testdata/workspaces/ws/ugh/package.json
internal/guidedremediation/manifest/npm/testdata/workspaces/z/package.json
internal/guidedremediation/resolution/dependency_subgraph.go
internal/guidedremediation/resolution/requirement_key.go
internal/guidedremediation/resolution/resolve.go
internal/mavenutil/maven.go

Copied over package.json/pom.xml manifest parsing from osv-scanner.
Haven't yet moved the package-lock.json graph parsing, nor the writing parts.

feat(guided remediation): Manifest parsing

---

clients/datasource/maven_registry.go
extractor/filesystem/language/java/pomxmlnet/pomxmlnet.go

The Maven Central mirror is not a actively maintained service so let's still use the Maven Central repository.

fix: use Maven Central as registry for pomxmlnet extractor

---

common/linux/proc/process_linux.go

I think my understanding here is correct enough, though I feel like ideally `extractSocketInode` should be returning a sentinel error rather than 0 (which I assume is being used as it is the sentinel value used by Linux to indicate there isn't an inode); in addition to that requiring a bit more code, I figure it might be possible for the function to end up with 0 anyway meaning we couldn't just get rid of the `inode != 0` ...
Ultimately, I'm just looking to get CI green again so happy to go in whatever direction(s) others would prefer (including what's written in the comments)

chore: ignore `nilerr` violations relating to linux process extractor

---

artifact/image/layerscanning/image/image.go
artifact/image/layerscanning/image/image_test.go
artifact/image/unpack/unpack.go

This makes the linter happy - technically only the change to `artifact/image/layerscanning/image/image_test.go` is needed for that, but I don't see any reason why `archive/tar` should be in its own dedicated group so I've checked the rest of the codebase too

refactor: sort imports

---

artifact/image/layerscanning/trace/trace.go

The previous layer is no longer always the layer that we last read and found the package in layer tracing. We keep track of the actual last layer scanned, and use that as the origin layer index when the package cannot be found.
Ideally we also add some unit test cases to catch this.
Tested this change in osv-scanner and it seems to fix the issue.

fix: layer tracing logic after optimisation

---

.golangci.yaml
detector/weakcredentials/filebrowser/filebrowser.go

chore: ensure that JSON errors are properly checked when required

---

artifact/image/layerscanning/image/image.go
common/linux/proc/process_linux.go
extractor/filesystem/containers/containerd/containerd_linux.go
extractor/filesystem/language/dotnet/depsjson/depsjson.go
extractor/filesystem/language/dotnet/packagesconfig/packagesconfig.go
extractor/filesystem/language/dotnet/packageslockjson/packageslockjson.go
extractor/filesystem/language/elixir/mixlock/mixlock.go
extractor/filesystem/language/python/condameta/condameta.go
extractor/filesystem/language/python/requirements/requirements.go
extractor/filesystem/language/swift/packageresolved/packageresolved.go
extractor/filesystem/language/swift/podfilelock/podfilelock.go
extractor/filesystem/os/cos/cos.go
extractor/filesystem/os/kernel/module/module.go
extractor/filesystem/os/kernel/vmlinuz/vmlinuz.go
extractor/filesystem/os/macapps/macapps.go
extractor/filesystem/os/portage/portage.go
extractor/filesystem/os/snap/snap.go
extractor/standalone/os/netports/netports_linux.go

As none of these parameters are used by their respective functions, they can be safely removed without issue.
In the long run the `unparam` linter will help catch this for us.

refactor: remove unused params from internal functions

---

.golangci.yaml

[We've decided to disable this linter for now](https://github.com/google/osv-scalibr/pull/525#issuecomment-2702397088) as it's likely going to be very annoying without the internal linter enforcing it

chore: disable `nlreturn` linter

---

go.mod
go.sum

This resolves an issue when running `go list` (which IDEs use in particular) due to an invalid reference being introduced upstream: https://github.com/google/deps.dev/pull/203

fix: update `deps.dev/util/resolve`

---

detector/cve/cve20236019/cve20236019.go

Even if we feel this is needed, the method itself is deprecated in favor of creating a local generator with a specific seed

refactor: remove unneeded random seeding, as `Seed` is now already randomized since Go v1.20

---

.golangci.yaml
detector/cve/cve202011978/cve202011978.go
detector/cve/cve202016846/cve202016846.go
detector/cve/cve202233891/cve202233891.go
detector/cve/cve20236019/cve20236019.go
detector/cve/cve20242912/cve20242912.go
detector/weakcredentials/filebrowser/filebrowser.go

IPv6 addresses need to be wrapped in square brackets when a port is being specified which `net.JoinHostPort` takes care of automatically.
This also enables the `nosprintfhostport` linter to catch this going forward.

fix: ensure that `host:port` joining is done correct for IPv6 addresses

---

.golangci.yaml

This mirrors an internal linter, so unsurprisingly we've not got any actual violations.
Note that by configuring `revive` at all we override its default rules, some of which we'll want enabled long-term
Relates to #455

chore: ensure that `any` is used instead of `interface{}`

---

.golangci.yaml

#539 addressed the only violation, so we can now enable this

chore: enable `staticcheck` linter

---

.golangci.yaml
detector/cve/cve202011978/cve202011978.go
detector/cve/cve202016846/cve202016846.go

This also enables the `noctx` lint to enforce this in future

fix: always provide a context when making http requests

---

.golangci.yaml
artifact/image/layerscanning/image/file_node_test.go
artifact/image/layerscanning/image/image.go
artifact/image/layerscanning/image/image_test.go
artifact/image/layerscanning/image/layer_test.go
artifact/image/tar/tar_test.go
artifact/image/unpack/unpack.go
artifact/image/unpack/unpack_test.go
clients/datasource/cache_test.go
clients/datasource/http_auth.go
common/windows/registry/offline.go
detector/weakcredentials/etcshadow/etcshadow.go
extractor/filesystem/containers/containerd/containerd_test.go
extractor/filesystem/internal/walkdir_iterate_test.go
extractor/filesystem/language/java/archive/archive_test.go
extractor/filesystem/language/java/archive/manifest.go
extractor/filesystem/os/apk/apk_test.go
extractor/filesystem/os/cos/cos_test.go
extractor/filesystem/os/dpkg/dpkg_test.go
extractor/filesystem/os/flatpak/flatpak_test.go
extractor/filesystem/os/kernel/module/module_test.go
extractor/filesystem/os/kernel/vmlinuz/vmlinuz_test.go
extractor/filesystem/os/nix/nix_test.go
extractor/filesystem/os/osrelease/osrelease_test.go
extractor/filesystem/os/pacman/pacman_test.go
extractor/filesystem/os/portage/portage_test.go
extractor/filesystem/os/rpm/rpm_test.go
extractor/filesystem/os/snap/snap_test.go
internal/guidedremediation/resolution/resolve_test.go
scalibr_test.go

This enables the `errcheck` linter which enforces errors be either handled or explicitly ignored to make it clear that the error handling has been thought about rather than mistakenly forgotten.

refactor: explicitly ignore errors that we don't need to handle

---

binary/cli/cli.go
binary/proto/proto.go
extractor/filesystem/language/golang/gobinary/gobinary.go
extractor/standalone/containers/containerd/containerd_linux.go
semantic/parse.go
semantic/version-cran.go
semantic/version-maven.go
semantic/version-nuget.go
semantic/version-packagist.go
semantic/version-redhat.go
semantic/version-rubygems.go
semantic/version-semver.go

Since none of these functions actually return an error value, we can remove that return entirely and in doing so remove a few error checks that would never be hit.
In the long run the `unparam` linter will help catch this for us.

refactor: remove unused error returns from internal functions

---

.golangci.yaml
detector/cve/cve20242912/cve20242912.go
extractor/filesystem/language/python/requirements/requirements.go
extractor/filesystem/os/rpm/rpm_linux.go

This helps makes code more readable by avoiding unneeded indenting

refactor: remove unneeded `else` blocks

---

detector/cve/cve202338408/cve202338408.go

Branched off of #496
Addresses https://github.com/google/osv-scalibr/pull/496#discussion_r1975347447

fix: don't panic if openSSH version cannot be parsed

---

extractor/filesystem/language/golang/gomod/gomod.go
extractor/filesystem/language/golang/gomod/gomod_test.go
extractor/filesystem/language/golang/gomod/testdata/toolchain-with-suffix.mod
extractor/filesystem/language/golang/gomod/testdata/toolchain.mod

Unlike with `go`, the `toolchain` directive holds the name of an actual toolchain which is prefixed with `go` and can have a suffix - when comparing, [these should be ignored](https://go.dev/doc/toolchain#name):
> Toolchains are compared by comparing the version V embedded in the name (dropping the initial go and discarding off any suffix beginning with -)
~However, I'm not sure if that's an extractor-level concern - if it's not, then I think we'll need to include a custom version comparator for `semantic` to handle that, and ensure comparators elsewhere like osv.dev account for this.~
Resolves https://github.com/google/osv-scanner/issues/1606

fix(gomod): prefer version specified by `toolchain` directive when present

---

.golangci.yaml
clients/datasource/internal/pypi/pypi.go
clients/datasource/pypi_registry.go
clients/datasource/pypi_registry_test.go
clients/resolution/pypi_registry_client.go
extractor/standalone/containers/containerd/containerd_test.go

This enables the `var-naming` rule within `revive`, which by default mirrors `golint`

refactor: prefer "ID" and "JSON" instead of "Id" and "Json"

---

.github/workflows/go.yml

Because the linter involves compiling files, it won't lint files that are excluded due to `go:build` directives, so we really should be running the linter across all three OSs - currently running on Windows works but has a number of errors mostly around imports that I suspect are due to file path and line ending differences, but macOS works fine so we might as well start running on that

ci: run linter on `macos-latest`

---

detector/cve/cve202011978/cve202011978.go

I'm pretty sure this is technically a bug, though it might not actually be causing problems as `res` might still not be `nil` in which case I'd expect the JSON decode straight afterwards to fail and return, rather than a panic.
Regardless though I think this should still be returning

fix: return after encountering an error when trying to talk to DAG

---

.golangci.yaml

This enables most of the default `revive` rules which we don't have any violations for.
The remaining ones to be enabled which do have violations are:
- ~`indent-error-flow` (https://github.com/google/osv-scalibr/pull/562)~
- `exported`
- `package-name` (https://github.com/google/osv-scalibr/pull/547)
- `unexported-return`
- `unused-parameter`
- `var-declaration`
- `var-naming` (https://github.com/google/osv-scalibr/pull/563)

chore: enable more `revive` rules

---

.golangci.yaml
detector/weakcredentials/winlocal/winlocal_dummy.go
extractor/standalone/windows/dismpatch/dismpatch_dummy.go
extractor/standalone/windows/ospackages/ospackages_dummy.go
extractor/standalone/windows/regosversion/regosversion_dummy.go
extractor/standalone/windows/regpatchlevel/regpatchlevel_dummy.go

This mirrors an internal linter, though this linter requires that the package comment be in a file that is not ignored e.g. due to `go:build` conditions, meaning it considers a few packages as missing comments as they're in a Windows-only file.
Currently, I've addressed that by copying the comment into a non-Windows file without removing the previous comment, though we might want to discuss what convention we actually follow - I think there's at least two possible ones to consider:
1. always put the comment in all files in a `go:build` "set" i.e. `xyz_dummy.go` and `xyz_windows.go` (downside being we're having to maintain the comment twice)
2. always put the package comment in a file that is never ignored when possible (possible downside is that often that can be a file holding utilities …

chore: ensure that all packages have comments

---

artifact/image/image.go
artifact/image/layerscanning/image/image_test.go
artifact/image/tar/tar.go
extractor/filesystem/containers/containerd/containerd_linux.go
extractor/filesystem/filesystem.go
extractor/filesystem/language/haskell/cabal/cabal.go
extractor/filesystem/language/haskell/stacklock/stacklock.go
extractor/filesystem/language/python/setup/setup.go
extractor/filesystem/language/rust/cargotoml/cargotoml.go
extractor/filesystem/os/apk/apk.go
extractor/filesystem/os/cos/cos.go
extractor/filesystem/os/dpkg/dpkg.go
extractor/filesystem/os/flatpak/flatpak.go
extractor/filesystem/os/kernel/module/module.go
extractor/filesystem/os/kernel/vmlinuz/vmlinuz.go
extractor/filesystem/os/nix/nix.go
extractor/filesystem/os/pacman/pacman.go
extractor/filesystem/os/snap/snap.go

By using `%w` errors can later be unwrapped with `errors.Unwrap`, allowing them to be checked with `errors.Is` and `errors.As`.
This will later be enforced by `errorlint`

fix: ensure errors are properly wrapped

---

artifact/image/layerscanning/testing/fakelayerbuilder/extractor.go
artifact/image/layerscanning/testing/fakelayerbuilder/fakelayerbuilder.go
artifact/image/layerscanning/testing/fakelayerbuilder/models.go
artifact/image/layerscanning/trace/testdata/populatelayers.yml
artifact/image/layerscanning/trace/trace_test.go

Created a yaml based fake layer definition to make it easier to setup tests, and also added a 5th chain layer to the test to showcase  how easy it is to add new layers.
No existing tests has been changed other than to set change the diff ID index from starting at "diff-1" to start at "diff-0" instead to match Index.
In this PR I avoided removing Inventory from the initial test cases to minimise changes, but it is a possible change in the future to make it easier to define additional test cases.
@mleyvajr100 PTAL!

tests: Yaml based false layers

---

guidedremediation/internal/strategy/override/override.go

The override strategy was sorting (i.e. modifying) the versions list returned by `client.Versions()`, which might be shared between goroutines.
Changed it to clone the slice if it needs to be sorted.

fix(guided remediation): data race in override strategy

---

extractor/filesystem/sbom/cdx/cdx.go
extractor/filesystem/sbom/cdx/cdx_test.go
extractor/filesystem/sbom/cdx/testdata/sbom-with-nested-comps.cdx.json

Fixes: https://github.com/google/osv-scanner/issues/1717
This adds support for extracting nested components. 
The new test file is indented with 2 spaces to follow the set editorconfig, but the other json files for this extractor are indented with 4. We'll have to do a pass to unify the indentation on all the test files at some point.

fix: CDX extractor should be extracting nested components

---

.github/workflows/go.yml

`go mod tidy -diff` will return a non-zero exit code if there are changes, allowing it to be used in CI to enforce our `go.sum` is tidy
Relates to #455

ci: ensure that `go.sum` is tidy

---

extractor/filesystem/sbom/cdx/cdx.go
extractor/filesystem/sbom/cdx/cdx_test.go
extractor/filesystem/sbom/cdx/testdata/minimal.cdx.json
extractor/filesystem/sbom/spdx/spdx_test.go
extractor/filesystem/sbom/spdx/testdata/minimal.spdx.json

Fixes https://github.com/google/osv-scanner/issues/1744
Because cdxBom.Components is a pointer to a slice, it's dereferenced before being passed to a for loop, causing it to panic when the component does not exist. Add an extra check here to prevent this. 
https://github.com/google/osv-scalibr/blob/b93cd317ad98c8677ae54bb2016a01c9759cb667/extractor/filesystem/sbom/cdx/cdx.go#L112-L120
Also added the file from the issue as a test case, and added a similarly empty SPDX test case as well just to be sure.

fix: Don't panic when extracting CDX with no components

---

extractor/standalone/windows/dismpatch/dismparser/dism_parser_test.go

This makes the test less brittle as it no longer cares about the exact wording of the error message

test: check for error instance rather than message

---

.golangci.yaml

chore: disable `nilnil` and `prealloc` linters

---

guidedremediation/internal/util/util.go
guidedremediation/internal/vulns/vulns.go

I'm pretty sure this was the intended name given both the function comment and that its counterpart is `DepsDevToOSVEcosystem`

refactor: rename `OSVToDepsDevSystem` to match opposite utility function

---

extractor/filesystem/language/java/pomxml/testdata/parent/pom.xml
internal/mavenutil/maven.go

`MergeParents` is called in pomxml extractor which does not require network access so Maven registry client is `nil`.
However, when there are repositories defined in a pom.xml, it still tries to add the information which causes `nil` pointer error.
This PR fixes this issue by checking if the client is nil before adding repository information.

fix: only add repositories in pomxml when client is not nil

---

detector/list/list.go
extractor/filesystem/list/list.go
extractor/standalone/list/list.go

It's not conventional to capitalize parameter names since capitalization is used to represent if something is public or private, and parameters are always local
This will be enforced by the `gocritic` linter

refactor: don't capitalize param names

---

.golangci.yaml

This makes it easier to maintain the linting configuration since new linters will automatically be enabled when we do updates rather than needing to explicitly determine what has been introduced

chore: enable all linters by default and disable the ones we don't want explicitly

---

binary/cli/cli.go
binary/proto/proto.go
detector/detector.go
extractor/filesystem/containers/containerd/containerd_linux.go
extractor/filesystem/language/python/wheelegg/wheelegg.go
extractor/filesystem/os/dpkg/dpkg.go
extractor/filesystem/os/macapps/macapps.go
extractor/standalone/containers/containerd/containerd_linux.go
extractor/standalone/windows/dismpatch/dismparser/dism_parser.go

Go convention is that error messages shouldn't be capitalized or end with punctuation as they might get chained
This will later be enforced by the `stylecheck` linter

refactor: don't capitalize error messages

---

artifact/image/layerscanning/image/image_test.go
detector/govulncheck/binary/binary.go

This are not needed, and will later be flagged by the `gocritic` linter

refactor: remove unneeded slice expressions

---

converter/converter.go

This are not needed, and will later be flagged by the `gocritic` linter

refactor: remove unneeded pointer dereferences

---

extractor/filesystem/language/python/requirements/requirements.go

Because this params are the wrong way round we currently check if `-` is prefixed with the line, which will never be true - this doesn't result in any actual issue right now because even though we can parse a version out depending on the string (e.g. if someone does something nonsensical like `-ipkg == 1.0.0`), because of the `-` the package name will never be considered valid.
However, in a future where we started capturing metrics those'd end up being incorrect, and right now we're wasting cycles parsing lines that will never be valid package.
This was caught by the `gocritic` linter

fix(requirements): actually check if line is a global option

---

extractor/standalone/windows/dismpatch/dismpatch.go

This will be enforced by the `gocritic` linter

refactor: use local variable to remove the need to cast again

---

.golangci.yaml
artifact/image/layerscanning/image/image.go
artifact/image/layerscanning/image/image_test.go
extractor/filesystem/containers/containerd/containerd_test.go
guidedremediation/guidedremediation.go

This linter checks for unused functions and parameters, and parameters that have only a single value which is why I've introduced a private global variable in the `containerd` test; that feels a little weird, but I think it's slightly better than having a linter disable comment given it's internal test code.
I've already addressed the main two classes of violations this linter caught in the codebase, so the actual net win for enabling this is the sum of this + these PRs:
* https://github.com/google/osv-scalibr/pull/520
* https://github.com/google/osv-scalibr/pull/519
* https://github.com/google/osv-scalibr/pull/500
There was one new violation that slipped through after #520 was landed, which I've also addressed here

chore: enable `unparam` linter

---

.golangci.yaml

chore: enable `errorlint` linter

---

.golangci.yaml
artifact/image/tar/tar_test.go
artifact/image/unpack/unpack_test.go
extractor/filesystem/language/java/archive/archive_test.go

This method handles automatically cleaning up the directory when tests are complete and errors with `t.Fatal` if the directory cannot be created, meaning less logic for us to maintain.
This is enforced by the `usetesting` linter

test: prefer using `t.TempDir` where possible

---

artifact/image/whiteout/whiteout.go

This is enforced by the `gocritic` linter, and is consistent with the rest of the codebase

refactor: use `+=` operator to add suffix to string

---

.golangci.yaml

I mistakenly removed this in #561
Relates to https://github.com/google/osv-scalibr/issues/274
Relates to #455

chore: enable `use-any` linter (again)

---

extractor/filesystem/language/elixir/mixlock/mixlock_test.go
extractor/filesystem/language/erlang/mixlock/mixlock_test.go
extractor/filesystem/language/erlang/mixlock/mixlockutils/mixlockutils.go

Intentionally or not, in every other extractor we return an empty slice rather than `nil` for this situation so I think it makes sense that we do so here.

fix(mixlock): always return a slice of inventories

---

.golangci.yaml
guidedremediation/internal/manifest/maven/pomxml.go
guidedremediation/internal/manifest/maven/pomxml_test.go

Note that this isn't actually a breaking change because the actual package is internal

refactor: don't prefix public things with their package name

---

extractor/filesystem/language/java/pomxml/pomxml.go
extractor/filesystem/language/java/pomxml/pomxml_test.go

Previously, version zero is returned if a dependency version cannot be identified in pom.xml, this is misleading and this PR leaves the version to be empty if it cannot be identified.

fix: return empty version if version cannot be identified in pomxml

---

guidedremediation/internal/vulns/vulns.go

Since we're already in an `else` branch, we can avoid a level of intention by using `else if`.
This will be later enforced by the `gocritic` linter

refactor: merge `if` with its `else` parent

---

clients/datasource/internal/pypi/pypi.go
clients/datasource/internal/pypi/pypi_test.go
clients/datasource/pypi_registry.go
clients/datasource/pypi_registry_test.go
clients/resolution/pypi_registry_client.go
clients/resolution/pypi_registry_client_test.go

Previously to decide whether a version is yanked or not, we fetch all version JSONs, however this slows down the dependency resolution.
In this PR, instead, we parse the index API response and decide whether a version is yanked or not by checking each file in the list.

feat: decide yanked from index API response

---

extractor/filesystem/language/python/requirements/requirements.go
extractor/filesystem/language/python/requirements/requirements_test.go

Previously, all locations are put into one singe string with `:` as the separator, however we would like the slice of locations instead. This PR fixes this by appending the initial path to the head of the location slice.

fix: do not put locations in one string for requirements extractor

---

clients/resolution/maven_registry_client.go
extractor/filesystem/language/java/pomxmlnet/pomxmlnet.go
guidedremediation/internal/manifest/maven/pomxml.go
internal/mavenutil/maven.go

When `mvn` fetches pom.xml for dependencies, it uses the repositories defined in effective pom which is generated by merging parent pom.xml, but not the repositories in remote dependency pom.xml. This does not match the behaviour we have in the Maven client and this PR fixes it by following `mvn`'s behaviour.

fix: only add registry to Maven client when merging parent pom.xml

---

clients/datasource/maven_registry.go
clients/datasource/maven_registry_test.go

If there is a repository with `central` ID defined in pom.xml it should overwrite the default Maven Central in [Super POM](https://maven.apache.org/ref/3.0.4/maven-model-builder/super-pom.html). 
In the Maven client, if the ID of a registry matches the default registry, the default registry will be updated. Also to prevent a repository without an ID to override the default registry, give the default registry an `default` ID.

feat: update the default registry of Maven client if ID matches

---

detector/detector.go
detector/detector/detectorrunner.go
detector/detector_test.go
detector/detectorrunner/detectorrunner.go
extractor/filesystem/filesystem.go
scalibr.go
stats/collector.go
stats/types.go

This patch allows the AfterExtractor function to get additional access to:
- Path
- Extractor's returned Inventory
And switched AfterExtractor to take a pointer to allow for future additions without making (big) breaking changes. 
Also had to move detector.Run into it's own package, separate from the type definitions to avoid cyclic dependency imports. This makes detector more similar to how extractors are laid out.
This needs to be patched once it's been approved to also update the internal implementation.

refactor: Pass inventory.Inventory to AfterExtractorRun

---

extractor/standalone/windows/dismpatch/dismparser/dism_parser.go

This was mistakenly reverted in #634 - there is actually at least one linter enabled that's meant to be enforcing this but it is not currently working properly for some reason; I'm looking into why that is, but for now just fixing this manually

refactor: use lowercase in error message

---

extractor/filesystem/language/python/requirementsnet/requirements.go
extractor/filesystem/language/python/requirementsnet/requirements_test.go
extractor/filesystem/language/python/requirementsnet/testdata/hash-checking.txt

https://github.com/google/osv-scalibr/issues/663
If any package in a requirements file has hashes, this indicates it's in [hash-checking mode](https://pip.pypa.io/en/stable/topics/secure-installs/#hash-checking-mode), and thus dependencies that are not listed in the requirements file won't be installed. 
In this PR, we skip dependency resolution for hash-checking mode so we don't waste efforts on resolving a potential lockfile.

feat: do not perform dependency resolution if requirements in hash-checking mode

---

extractor/annotator/annotator.go
extractor/annotator/cachedir.go
extractor/annotator/cachedir_test.go
scalibr.go
scalibr_test.go

This PRs contains the annotator package implementation, which adds annotations to the packages extracted from `scalibr`.
The implementation is pretty rough and minimal, feel free to leave suggestion on different ways to structure the code.

Annotate packages from cache directories

---

artifact/image/layerscanning/testing/fakelayerbuilder/extractor.go
extractor/standalone/containers/containerd/containerd_linux.go
extractor/standalone/containers/docker/docker.go

This will be enforced by the linter in the future

chore: make start of comment match exported thing

---

guidedremediation/result/result.go

This will be enforced by the linter in the future

chore: ensure package comment starts with capital "P"

---

extractor/filesystem/language/ruby/gemfilelock/gemfilelock.go

This will be enforced by the linter in the future
Relates to #455
Relates to #768

chore(extractor/gemfilelock): add comment to `Extract` method

---

extractor/filesystem/os/macapps/macapps.go
go.mod
go.sum

`github.com/groob/plist` redirects to [github.com/micromdm/plist](https://pkg.go.dev/github.com/micromdm/plist), which is the renamed package.

chore: use dependency github.com/micromdm/plist

---

extractor/filesystem/language/java/pomxmlnet/pomxmlnet.go
extractor/filesystem/language/python/requirementsnet/requirements.go

There may be graph-wide resolution [error](https://github.com/google/deps.dev/blob/main/util/resolve/graph.go#L67) in the resolve graph so we should return the error if it's not empty.

feat: also check error in the resolved graph

---

binary/cli/cli.go
binary/scalibr/scalibr.go
binary/scalibr/scalibr_test.go
converter/converter.go
converter/converter_test.go

Adds a flag name `cdx-component-type` to allow specifying the component type then generating CDX documents.
This PR relates to issue #802.

Add --cdx-component-type flag to SCALIBR.

---

extractor/filesystem/filesystem.go
stats/types.go

Add the scanRoot path to AfterExtractorRun, so I can get the full path of the file that was extracted in AfterExtractorRun.

feat: Write root path in AfterExtractorRun stats call

---

extractor/filesystem/language/java/archive/archive.go
extractor/filesystem/language/java/archive/archive_test.go

Java archive extractor returns `groupID` only as package names. To be consistent with other Java extractors, this PR includes `groupID` in package names for Java archive extractor.

fix: include groupID in package names returned by Java archive extractor

---

binary/cli/cli.go
clients/resolution/combined_native_client.go

Previously, ecosystem suffix is appended to the local registry all the time. By default, local registry is empty and this behaviour makes it non-empty so that the client will try to write the responses to the local file system. 
This PR fixes the behaviour by only appending the ecosystem suffix to non-empty local registry.

fix: append ecosystem suffix only when local registry is not empty

---

guidedremediation/internal/manifest/python/requirements.go
guidedremediation/internal/manifest/python/requirements_test.go
guidedremediation/internal/manifest/python/testdata/requirements.txt

https://github.com/google/osv-scalibr/issues/853
This PR adds a basic manifest reader for Python requirements file.

feat: manifest reader for Python requirements

---

artifact/image/layerscanning/image/image.go
artifact/image/layerscanning/image/pathtree.go

This filepath breaks windows container scanning, as it always considers you to not be in a whiteout dir.
We don't have a test in either osv-scalibr or osv-scanner that tests this, so we didn't catch it till #852 where we now return an error rather than silently dropping in cleanPath().
Blocking: https://github.com/google/osv-scanner/pull/2011

fix: filepath usage on windows breaking container scanning

---

.golangci.yaml
detector/govulncheck/binary/binary.go
extractor/filesystem/language/python/wheelegg/wheelegg_test.go
extractor/filesystem/secrets/secrets.go

refactor: remove unneeded zero-value initializations on `var` variables

---

guidedremediation/internal/manifest/python/requirements.go
guidedremediation/internal/manifest/python/requirements_test.go
guidedremediation/internal/manifest/python/testdata/want.requirements.txt

https://github.com/google/osv-scalibr/issues/853
This PR implements the writer for Python requirements.txt so that the new requirements can be written to the file.

feat: implement the manifest writer for Python requirements.txt

---

scalibr.go

The ordering of locations matter, so we should not sort the alphanumerically.

fix: don't sort locations on output

---

.golangci.yaml
artifact/image/layerscanning/image/image.go
artifact/image/layerscanning/trace/trace.go

Import aliases should follow the same conventions as package names for consistency

refactor: follow package naming conventions for import aliases

---

clients/resolution/pypi_registry_client.go
clients/resolution/pypi_registry_client_test.go

Related to https://github.com/google/osv-scanner/issues/2077
Previously, we only tried to parse the first file in the list for Python requirements, however, that file may be some format that we don't support. This causes error during dependency resolution.
Instead, this PR tries to parse the files in the list one by one until we successfully parse some requirements. This PR also changes logging level from Error to Warn for failures to parse requirements.

feat(pypi): try all available files to parse requirements

---

extractor/filesystem/sbom/cdx/cdx.go
extractor/filesystem/sbom/cdx/cdx_test.go
extractor/filesystem/sbom/cdx/metadata/metadata.go
extractor/filesystem/sbom/cdx/testdata/sbom-with-locations.cdx.json

This PR enhances the CycloneDX SBOM extractor as part of issue #893.
- Parsing JSON and XML CycloneDX files.
- Storing component location data in Metadata (not in top-level Locations).
- Adding unit tests for extraction and metadata preservation.
Closes #893

feat(cdx): extract CDX locations into metadata only [fixes #893]

---

extractor/filesystem/list/list.go

This is how we're using it in `osv-scanner` and it extracts from a binary like `gobinary` and friends do, so I'm pretty sure this should be classed as an artifact extractor rather than a source extractor

fix: classify `cargoauditable` as an artifact extractor

---

detector/cve/untested/cve202338408/cve202338408.go
guidedremediation/internal/tui/model/state_relock_result.go

This will be caught by the `noctx` linter in an upcoming version - I think its better to pass in `context.Background()` in cases where we cannot get a context from the caller due to interface restrictions, rather than disabling the linter, but happy to not do that if I'm wrong

fix: always use `exec.CommandContext`

---

enricher/reachability/java/java.go
enricher/reachability/java/reachable.go
enricher/reachability/java/utils.go

when performing an artifact scan, if the JAR path is an absolute path and the root path is `\`, the prefix should be stripped from the JAR path before doing `root.FS.open()`.

fix(enricher): strips root prefix from absolute jar paths

---

enricher/enricherlist/list.go

`All` is supposed to host the names of all enrichers.

feat(enricher): add all enrichers to the list

---

renovate.json

As Google does internal patching of Go dependencies for this library, we don't want Renovate always updating them to latest to avoid unnecessary churn.
I have also updated the config to match the format Renovate uses when it generates the config, and migrated us from `matchLanguages` to `matchCategories`

ci: update renovate config to not update Go dependencies

---

extractor/filesystem/language/php/composerlock/composerlock.go
extractor/filesystem/language/php/composerlock/composerlock_test.go
extractor/filesystem/language/php/composerlock/testdata/drupal-packages.json

Its possible for the `reference` field to contain values other than commits, such as for Drupal packages it holds a tag-type value.
Because I'm not sure all of the details behind when this will be the case, I've gone with having us blank the commit if the value has a dot in it since that is not a valid character in a SHA anyway, but this might not cover all situations e.g. if a branch-type value could be used.
Since we're hoping to soon have special handling for Drupal packages and I couldn't find non-Drupal package with this situation, I've used the test from #950 meaning that PR will just change the existing test case rather than add a new one 🤷 
I have also stretched this a little to encapsulate the package building in a dedicated function since its the same for dev and non-dev, and …

fix(composerlock): don't use `reference` as the commit if it contains a dot

---

detector/weakcredentials/winlocal/win32_windows.go

This was caught by `gocheckcompilerdirectives` running on Windows in #548

fix: remove space in compiler directive

---

binary/platform/platform_windows.go

This was caught by `revive` running on Windows in #548

refactor: remove unneeded default value

---

common/windows/registry/live.go

This was caught by `unused` running on Windows in #548

refactor: remove unused private field

---

extractor/standalone/windows/regpatchlevel/regpatchlevel_windows.go

This was caught by `errorlint` running on Windows in #548

fix: use `errors.Is` for checking error

---

clients/datasource/maven_registry.go

Previously, logging is added to all functions that call `get()`, but we do not always make requests (e.g. if the artifact is available from the local registry). What we actually care about is the actual HTTP requests we are making.

chore: reduce logging noise in Maven registry client

---

extractor/filesystem/language/javascript/packagelockjson/packagelockjson-v2_test.go
extractor/filesystem/language/javascript/packagelockjson/testdata/bundled-dependencies.v3.json
internal/dependencyfile/packagelockjson/packagelockjson.go

Despite what is said in the issue, it seems that the "bundled" status is only tracked in v2+ lockfiles 🤷 
Resolves #1283

feat(javascript/packagelockjson): mark bundled dependencies as being in the "bundled" group

---

semantic/testdata/redhat-versions.txt
semantic/version-redhat.go

RedHat versions follow the "e:v-r" format, which is a _subset_ of the "n-e:v-r.a" format [described in the blogpost I based my implementation off](https://blog.jasonantman.com/2014/07/how-yum-and-rpm-compare-versions/#how-rpm-compares-version-parts).
Notably, epochs are only such if they are a digit, otherwise it's all part of the version including the colon - in practice it seems this is very rare (which makes sense) but recently we've had some advisories published with versions that do use the colon, which revealed this bug

fix(semantic): handle Red Hat versions with colons but not epochs

---

.golangci.yaml

Unfortunately it's not possible to disable this check for tests only, but it's still better than having the whole linter disabled

ci: disable specific staticcheck check instead of the whole linter

---

.github/workflows/go.yml

This should ensure that files are valid across OSs - I've gone with an inclusive pattern which purposely does not have some characters that are technically legal but that I don't think there's a good reason to use them in a filename.

ci: add job for checking filenames
